a1.out: DamenProblem_1.cpp
	g++ -std=c++17 -o a1.out DamenProblem_1.cpp
run1: a1.out
	./a1.out

a2.out: DamenProblem_2.cpp
	g++ -std=c++17 -o a2.out DamenProblem_2.cpp
run2: a2.out
	./a2.out

.PHONY: clean

clean:
	rm a1.out
	rm a2.out